version: '3.5'

services:
  express:
    image: mongo-express:0.54
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-0,mongo-1,mongo-2
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'

      ME_CONFIG_MONGODB_AUTH_USERNAME: ''
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ''
      ME_CONFIG_MONGODB_URL: mongodb://mongo-0:27017,mongo-1:27017,mongo-2:27017/
    ports:
      - 8081:8081
    networks:
      - mongo

networks:
  mongo:
    external: true
